'use client';

import { Moon, Sun, Menu, Wrench, Trash2, Download, Save, Home, FileText } from 'lucide-react';
import { useTheme } from 'next-themes';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { useChatStore } from '@/store/chat-store';
import { jsPDF } from 'jspdf';

interface HeaderProps {
  onToolsClick: () => void;
  showHomeButton?: boolean;
  onHomeClick?: () => void;
}

export function Header({ onToolsClick, showHomeButton, onHomeClick }: HeaderProps) {
  const { theme, setTheme } = useTheme();
  const { messages, clearMessages } = useChatStore();

  const handleDownloadChat = () => {
    if (messages.length === 0) return;
    
    const chatText = messages
      .map((msg) => `${msg.role === 'user' ? 'You' : 'Brutal.ai'}: ${msg.content}`)
      .join('\n\n');
    
    const blob = new Blob([chatText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `brutal-ai-chat-${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadPDF = () => {
    if (messages.length === 0) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 15;
    const maxWidth = pageWidth - margin * 2;
    let yPosition = 20;
    const lineHeight = 6;

    // Title
    doc.setFontSize(18);
    doc.setTextColor(173, 255, 47); // Phosphor green
    doc.text('Brutal.ai Chat Export', margin, yPosition);
    yPosition += 12;

    // Date
    doc.setFontSize(10);
    doc.setTextColor(128, 128, 128);
    doc.text(`Exported on: ${new Date().toLocaleString()}`, margin, yPosition);
    yPosition += 15;

    // Messages
    doc.setFontSize(11);
    
    messages.forEach((msg) => {
      const isUser = msg.role === 'user';
      const label = isUser ? 'You' : 'Brutal.ai';
      
      // Check if we need a new page
      if (yPosition > 270) {
        doc.addPage();
        yPosition = 20;
      }
      
      // Role label
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(isUser ? 173 : 80, isUser ? 255 : 80, isUser ? 47 : 80);
      doc.text(label + ':', margin, yPosition);
      yPosition += lineHeight;
      
      // Message content
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(50, 50, 50);
      
      const lines = doc.splitTextToSize(msg.content, maxWidth);
      lines.forEach((line: string) => {
        if (yPosition > 280) {
          doc.addPage();
          yPosition = 20;
        }
        doc.text(line, margin, yPosition);
        yPosition += lineHeight;
      });
      
      yPosition += 5; // Space between messages
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(173, 255, 47);
    doc.text('Generated by Brutal.ai - Smarter. Faster. Brutal.', margin, 290);

    doc.save(`brutal-ai-chat-${new Date().toISOString().slice(0, 10)}.pdf`);
  };

  const handleSaveChat = () => {
    if (messages.length === 0) return;
    
    const chatData = JSON.stringify({
      messages,
      savedAt: new Date().toISOString(),
    });
    
    localStorage.setItem('brutal-ai-saved-chat', chatData);
  };

  return (
    <header className="sticky top-0 z-50 w-full border-b-2 border-black dark:border-[#333] bg-background">
      <div className="flex h-14 items-center justify-between px-4">
        {/* Logo */}
        <div className="flex items-center gap-3">
          {showHomeButton && onHomeClick && (
            <Button
              variant="ghost"
              size="icon"
              onClick={onHomeClick}
              className="h-9 w-9 border-2 border-black dark:border-[#333] hover:border-[#F97316]"
              title="Back to Home"
            >
              <Home className="h-4 w-4" />
            </Button>
          )}
          <img 
            src="/logo.png" 
            alt="Brutal.ai" 
            className="h-8 w-8 border-2 border-black dark:border-[#F97316]"
          />
          <div className="flex flex-col leading-tight">
            <span className="text-base font-black tracking-tight text-foreground">BRUTAL.AI</span>
            <span className="text-[10px] text-[#F97316] font-bold hidden sm:block tracking-wider uppercase">Smarter. Faster. Brutal.</span>
          </div>
        </div>

        {/* Actions */}
        <div className="flex items-center gap-2">
          <Button
            variant="ghost"
            size="icon"
            onClick={onToolsClick}
            className="h-9 w-9 border-2 border-black dark:border-[#333] hover:border-[#F97316]"
            title="AI Tools"
          >
            <Wrench className="h-4 w-4" />
          </Button>

          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" size="icon" className="h-9 w-9 border-2 border-black dark:border-[#333] hover:border-[#F97316]">
                <Menu className="h-4 w-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-48 border-2 border-black dark:border-[#333]">
              <DropdownMenuItem onClick={handleSaveChat} className="font-bold cursor-pointer">
                <Save className="mr-2 h-4 w-4" />
                Save Chat
              </DropdownMenuItem>
              <DropdownMenuSeparator className="bg-black/10 dark:bg-white/10" />
              <DropdownMenuItem onClick={handleDownloadChat} className="font-bold cursor-pointer">
                <Download className="mr-2 h-4 w-4" />
                Download as TXT
              </DropdownMenuItem>
              <DropdownMenuItem onClick={handleDownloadPDF} className="font-bold cursor-pointer">
                <FileText className="mr-2 h-4 w-4" />
                Download as PDF
              </DropdownMenuItem>
              <DropdownMenuSeparator className="bg-black/10 dark:bg-white/10" />
              <DropdownMenuItem 
                onClick={clearMessages}
                className="text-red-500 focus:text-red-500 font-bold cursor-pointer"
              >
                <Trash2 className="mr-2 h-4 w-4" />
                Clear Chat
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>

          <Button
            variant="ghost"
            size="icon"
            onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}
            className="h-9 w-9 border-2 border-black dark:border-[#333] hover:border-[#F97316]"
          >
            <Sun className="h-4 w-4 rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
            <Moon className="absolute h-4 w-4 rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
          </Button>
        </div>
      </div>
    </header>
  );
}
